// <auto-generated />
namespace WEB_BASE.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addFavoriteColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFavoriteColor));
        
        string IMigrationMetadata.Id
        {
            get { return "201406162033395_addFavoriteColor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
