// <auto-generated />
namespace BASE_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201410080022048_InitialConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
