//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PROFILE_CLASS
    {
        public int ClassID { get; set; }
        public int ProfileID { get; set; }
        public int ModuleID { get; set; }
    }
}
