//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_MODULES
    {
        public int ModuleID { get; set; }
        public string ModuleDescription { get; set; }
        public Nullable<int> ParentModuleID { get; set; }
        public string AssociateForm { get; set; }
        public string Activated { get; set; }
        public string CloseForm { get; set; }
        public string ParentModuleDescription { get; set; }
        public Nullable<int> Ordem { get; set; }
        public int ImageIndex { get; set; }
    }
}
