using System;
using System.Collections.Generic;

namespace WEB_BASE.Models
{
    public class Icons
    {
        public string Icon { get; set; }
    }

    public class Util
    {
        public List<String> GetAllColors()
        {
            return new List<String>
            {
                "Verde",
                "Vermelho",
                "Amarelo",
                "Azul",
                "Rosa",
                "Marron",
                "Preto",
                "Roxo"
            };
        }

        public List<Icons> GetAllIcons()
        {
            return new List<Icons>
            {
                new Icons{Icon =  ""},
                new Icons{Icon =  "glyphicon-asterisk"},
                new Icons{Icon =  "glyphicon-plus"},
                new Icons{Icon =  "glyphicon-euro"},
                new Icons{Icon =  "glyphicon-minus"},
                new Icons{Icon =  "glyphicon-cloud"},
                new Icons{Icon =  "glyphicon-pencil"},
                new Icons{Icon =  "glyphicon-glass"},
                new Icons{Icon =  "glyphicon-music"},
                new Icons{Icon =  "glyphicon-heart"},
                new Icons{Icon =  "glyphicon-star"},
                new Icons{Icon =  "glyphicon-star-empty"},
                new Icons{Icon =  "glyphicon-user"},
                new Icons{Icon =  "glyphicon-film"},
                new Icons{Icon =  "glyphicon-th-large"},
                new Icons{Icon =  "glyphicon-th"},
                new Icons{Icon =  "glyphicon-th-list"},
                new Icons{Icon =  "glyphicon-ok"},
                new Icons{Icon =  "glyphicon-remove"},
                new Icons{Icon =  "glyphicon-zoom-in"},
                new Icons{Icon =  "glyphicon-zoom-out"},
                new Icons{Icon =  "glyphicon-off"},
                new Icons{Icon =  "glyphicon-signal"},
                new Icons{Icon =  "glyphicon-cog"},
                new Icons{Icon =  "glyphicon-trash"},
                new Icons{Icon =  "glyphicon-home"},
                new Icons{Icon =  "glyphicon-file"},
                new Icons{Icon =  "glyphicon-time"},
                new Icons{Icon =  "glyphicon-road"},
                new Icons{Icon =  "glyphicon-download-alt"},
                new Icons{Icon =  "glyphicon-download"},
                new Icons{Icon =  "glyphicon-upload"},
                new Icons{Icon =  "glyphicon-inbox"},
                new Icons{Icon =  "glyphicon-play-circle"},
                new Icons{Icon =  "glyphicon-repeat"},
                new Icons{Icon =  "glyphicon-refresh"},
                new Icons{Icon =  "glyphicon-list-alt"},
                new Icons{Icon =  "glyphicon-lock"},
                new Icons{Icon =  "glyphicon-flag"},
                new Icons{Icon =  "glyphicon-headphones"},
                new Icons{Icon =  "glyphicon-volume-off"},
                new Icons{Icon =  "glyphicon-volume-down"},
                new Icons{Icon =  "glyphicon-volume-up"},
                new Icons{Icon =  "glyphicon-qrcode"},
                new Icons{Icon =  "glyphicon-barcode"},
                new Icons{Icon =  "glyphicon-tag"},
                new Icons{Icon =  "glyphicon-tags"},
                new Icons{Icon =  "glyphicon-book"},
                new Icons{Icon =  "glyphicon-bookmark"},
                new Icons{Icon =  "glyphicon-print"},
                new Icons{Icon =  "glyphicon-camera"},
                new Icons{Icon =  "glyphicon-font"},
                new Icons{Icon =  "glyphicon-bold"},
                new Icons{Icon =  "glyphicon-italic"},
                new Icons{Icon =  "glyphicon-text-height"},
                new Icons{Icon =  "glyphicon-text-width"},
                new Icons{Icon =  "glyphicon-align-left"},
                new Icons{Icon =  "glyphicon-align-center"},
                new Icons{Icon =  "glyphicon-align-right"},
                new Icons{Icon =  "glyphicon-align-justify"},
                new Icons{Icon =  "glyphicon-list"},
                new Icons{Icon =  "glyphicon-indent-left"},
                new Icons{Icon =  "glyphicon-indent-right"},
                new Icons{Icon =  "glyphicon-facetime-video"},
                new Icons{Icon =  "glyphicon-picture"},
                new Icons{Icon =  "glyphicon-map-marker"},
                new Icons{Icon =  "glyphicon-adjust"},
                new Icons{Icon =  "glyphicon-tint"},
                new Icons{Icon =  "glyphicon-edit"},
                new Icons{Icon =  "glyphicon-share"},
                new Icons{Icon =  "glyphicon-check"},
                new Icons{Icon =  "glyphicon-move"},
                new Icons{Icon =  "glyphicon-step-backward"},
                new Icons{Icon =  "glyphicon-fast-backward"},
                new Icons{Icon =  "glyphicon-backward"},
                new Icons{Icon =  "glyphicon-play"},
                new Icons{Icon =  "glyphicon-pause"},
                new Icons{Icon =  "glyphicon-stop"},
                new Icons{Icon =  "glyphicon-forward"},
                new Icons{Icon =  "glyphicon-fast-forward"},
                new Icons{Icon =  "glyphicon-step-forward"},
                new Icons{Icon =  "glyphicon-eject"},
                new Icons{Icon =  "glyphicon-chevron-left"},
                new Icons{Icon =  "glyphicon-chevron-right"},
                new Icons{Icon =  "glyphicon-plus-sign"},
                new Icons{Icon =  "glyphicon-minus-sign"},
                new Icons{Icon =  "glyphicon-remove-sign"},
                new Icons{Icon =  "glyphicon-ok-sign"},
                new Icons{Icon =  "glyphicon-question-sign"},
                new Icons{Icon =  "glyphicon-info-sign"},
                new Icons{Icon =  "glyphicon-screenshot"},
                new Icons{Icon =  "glyphicon-remove-circle"},
                new Icons{Icon =  "glyphicon-ok-circle"},
                new Icons{Icon =  "glyphicon-ban-circle"},
                new Icons{Icon =  "glyphicon-arrow-left"},
                new Icons{Icon =  "glyphicon-arrow-right"},
                new Icons{Icon =  "glyphicon-arrow-up"},
                new Icons{Icon =  "glyphicon-arrow-down"},
                new Icons{Icon =  "glyphicon-share-alt"},
                new Icons{Icon =  "glyphicon-resize-full"},
                new Icons{Icon =  "glyphicon-resize-small"},
                new Icons{Icon =  "glyphicon-exclamation-sign"},
                new Icons{Icon =  "glyphicon-gift"},
                new Icons{Icon =  "glyphicon-leaf"},
                new Icons{Icon =  "glyphicon-fire"},
                new Icons{Icon =  "glyphicon-eye-open"},
                new Icons{Icon =  "glyphicon-eye-close"},
                new Icons{Icon =  "glyphicon-warning-sign"},
                new Icons{Icon =  "glyphicon-plane"},
                new Icons{Icon =  "glyphicon-calendar"},
                new Icons{Icon =  "glyphicon-random"},
                new Icons{Icon =  "glyphicon-comment"},
                new Icons{Icon =  "glyphicon-magnet"},
                new Icons{Icon =  "glyphicon-chevron-up"},
                new Icons{Icon =  "glyphicon-chevron-down"},
                new Icons{Icon =  "glyphicon-retweet"},
                new Icons{Icon =  "glyphicon-shopping-cart"},
                new Icons{Icon =  "glyphicon-folder-close"},
                new Icons{Icon =  "glyphicon-folder-open"},
                new Icons{Icon =  "glyphicon-resize-vertical"},
                new Icons{Icon =  "glyphicon-resize-horizontal"},
                new Icons{Icon =  "glyphicon-hdd"},
                new Icons{Icon =  "glyphicon-bullhorn"},
                new Icons{Icon =  "glyphicon-bell"},
                new Icons{Icon =  "glyphicon-certificate"},
                new Icons{Icon =  "glyphicon-thumbs-up"},
                new Icons{Icon =  "glyphicon-thumbs-down"},
                new Icons{Icon =  "glyphicon-hand-right"},
                new Icons{Icon =  "glyphicon-hand-left"},
                new Icons{Icon =  "glyphicon-hand-up"},
                new Icons{Icon =  "glyphicon-hand-down"},
                new Icons{Icon =  "glyphicon-circle-arrow-right"},
                new Icons{Icon =  "glyphicon-circle-arrow-left"},
                new Icons{Icon =  "glyphicon-circle-arrow-up"},
                new Icons{Icon =  "glyphicon-circle-arrow-down"},
                new Icons{Icon =  "glyphicon-globe"},
                new Icons{Icon =  "glyphicon-wrench"},
                new Icons{Icon =  "glyphicon-tasks"},
                new Icons{Icon =  "glyphicon-filter"},
                new Icons{Icon =  "glyphicon-briefcase"},
                new Icons{Icon =  "glyphicon-fullscreen"},
                new Icons{Icon =  "glyphicon-dashboard"},
                new Icons{Icon =  "glyphicon-paperclip"},
                new Icons{Icon =  "glyphicon-heart-empty"},
                new Icons{Icon =  "glyphicon-link"},
                new Icons{Icon =  "glyphicon-phone"},
                new Icons{Icon =  "glyphicon-pushpin"},
                new Icons{Icon =  "glyphicon-usd"},
                new Icons{Icon =  "glyphicon-gbp"},
                new Icons{Icon =  "glyphicon-sort"},
                new Icons{Icon =  "glyphicon-sort-by-alphabet"},
                new Icons{Icon =  "glyphicon-sort-by-alphabet-alt"},
                new Icons{Icon =  "glyphicon-sort-by-order"},
                new Icons{Icon =  "glyphicon-sort-by-order-alt"},
                new Icons{Icon =  "glyphicon-sort-by-attributes"},
                new Icons{Icon =  "glyphicon-sort-by-attributes-alt"},
                new Icons{Icon =  "glyphicon-unchecked"},
                new Icons{Icon =  "glyphicon-expand"},
                new Icons{Icon =  "glyphicon-collapse-down"},
                new Icons{Icon =  "glyphicon-collapse-up"},
                new Icons{Icon =  "glyphicon-log-in"},
                new Icons{Icon =  "glyphicon-flash"},
                new Icons{Icon =  "glyphicon-log-out"},
                new Icons{Icon =  "glyphicon-new-window"},
                new Icons{Icon =  "glyphicon-record"},
                new Icons{Icon =  "glyphicon-save"},
                new Icons{Icon =  "glyphicon-open"},
                new Icons{Icon =  "glyphicon-saved"},
                new Icons{Icon =  "glyphicon-import"},
                new Icons{Icon =  "glyphicon-export"},
                new Icons{Icon =  "glyphicon-send"},
                new Icons{Icon =  "glyphicon-floppy-disk"},
                new Icons{Icon =  "glyphicon-floppy-saved"},
                new Icons{Icon =  "glyphicon-floppy-remove"},
                new Icons{Icon =  "glyphicon-floppy-save"},
                new Icons{Icon =  "glyphicon-floppy-open"},
                new Icons{Icon =  "glyphicon-credit-card"},
                new Icons{Icon =  "glyphicon-transfer"},
                new Icons{Icon =  "glyphicon-cutlery"},
                new Icons{Icon =  "glyphicon-header"},
                new Icons{Icon =  "glyphicon-compressed"},
                new Icons{Icon =  "glyphicon-earphone"},
                new Icons{Icon =  "glyphicon-phone-alt"},
                new Icons{Icon =  "glyphicon-tower"},
                new Icons{Icon =  "glyphicon-stats"},
                new Icons{Icon =  "glyphicon-sd-video"},
                new Icons{Icon =  "glyphicon-hd-video"},
                new Icons{Icon =  "glyphicon-subtitles"},
                new Icons{Icon =  "glyphicon-sound-stereo"},
                new Icons{Icon =  "glyphicon-sound-dolby"},
                new Icons{Icon =  "glyphicon-sound-5-1"},
                new Icons{Icon =  "glyphicon-sound-6-1"},
                new Icons{Icon =  "glyphicon-sound-7-1"},
                new Icons{Icon =  "glyphicon-copyright-mark"},
                new Icons{Icon =  "glyphicon-registration-mark"},
                new Icons{Icon =  "glyphicon-cloud-download"},
                new Icons{Icon =  "glyphicon-cloud-upload"},
                new Icons{Icon =  "glyphicon-tree-conifer"},
                new Icons{Icon =  "glyphicon-tree-deciduous"}
            };
        }
    }
}