// <auto-generated />
namespace WEB_BASE.DataContexts.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterNameTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterNameTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201406200000377_AlterNameTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
